### create todo
POST {{BASE_URL}}/todos
Authorization: Bearer {{$global.accessToken}}
Content-Type: application/json
{
  "title":"example todo",
  "description":"ini adalah contoh descripsi"
}

### get all todo
GET {{BASE_URL}}/todos
Authorization: Bearer {{$global.accessToken}}

### get todo by id
GET {{BASE_URL}}/todos/2ed49d8c-67b6-4274-9de8-156dfbbc47e2
Authorization: Bearer {{$global.accessToken}}

### update todos
PUT {{BASE_URL}}/todos/2ed49d8c-67b6-4274-9de8-156dfbbc47e2
Authorization: Bearer {{$global.accessToken}}
Content-Type: application/json
{
  "title":"example todo",
  "description":"ini adalah contoh descripsi"
}

### delete todos
DELETE {{BASE_URL}}/todos/xnm7Eg3weTyhyNIFUsugX
Authorization: Bearer {{$global.accessToken}}