### create todo
POST {{BASE_URL}}/todos
Authorization: Bearer {{$global.accessToken}}
Content-Type: application/json
{
  "title":"example todo",
  "description":"ini adalah contoh descripsi"
}

### get all todo
GET {{BASE_URL}}/todos
Authorization: Bearer {{$global.accessToken}}

### get todo by id
GET {{BASE_URL}}/todos/1be1fd7a-abc4-49c9-8c89-55ba470f1c29
Authorization: Bearer {{$global.accessToken}}

### update todos
PUT {{BASE_URL}}/todos/1be1fd7a-abc4-49c9-8c89-55ba470f1c29
Authorization: Bearer {{$global.accessToken}}
Content-Type: application/json
{
  "title":"example todo",
  "description":"ini adalah contoh descripsi"
}

### delete todos
DELETE {{BASE_URL}}/todos/69bb6c9f-9414-403c-a000-c96630dbd2c1
Authorization: Bearer {{$global.accessToken}}