
### create user
POST {{BASE_URL}}/users
Content-Type: application/json
{
  "name":"Pojok Code",
  "email":"code@gmail.com",
  "password":"P@ssw0rd123"
}

### get all user
GET {{BASE_URL}}/users
Authorization: Bearer {{$global.accessToken}}
### get user by id
GET {{BASE_URL}}/users/71f6711c-b778-435f-b97c-fc3d876ed7fc
Authorization: Bearer {{$global.accessToken}}
### update user
PUT {{BASE_URL}}/users/71f6711c-b778-435f-b97c-fc3d876ed7fc
Authorization: Bearer {{$global.accessToken}}
Content-Type: application/json
{
  "name":"Pojok Code",
  "email":"code@gmail.com",
  "password":"P@ssw0rd123"
}

### delete user
DELETE {{BASE_URL}}/users/71f6711c-b778-435f-b97c-fc3d876ed7fc
Authorization: Bearer {{$global.accessToken}}

### user login
POST {{BASE_URL}}/login
{
  "email":"code@gmail.com",
  "password":"P@ssw0rd123"
}

{{
  $global.accessToken=JSON.parse(response.body).data.accessToken;
}}
